theme = "base16_transparent"

[editor]
true-color = true
line-number = "relative"
mouse = true
middle-click-paste = true
scroll-lines = 3
shell = ["sh", "-c"]
text-width = 100
completion-trigger-len = 2
auto-completion = true
auto-format = true
auto-save = true
idle-timeout = 250
completion-timeout = 250
preview-completion-insert = true
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["file-type"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = "↪ "

[keys.normal]
# Quick save
C-s = ":write"
# Quick quit
C-q = ":quit"
# Format document
C-f = ":format"
# Go to definition
g = { d = "goto_definition", r = "goto_reference", i = "goto_implementation", t = "goto_type_definition" }
# Rename symbol
F2 = "rename_symbol"
# Code actions
space = { a = "code_action", f = ":format" }
# Toggle comments
"C-/" = "toggle_comments"
# Window commands submenu
"C-w" = { h = ":hsplit", v = ":vsplit", c = ":buffer-close" }
# Buffer navigation
"C-n" = ":buffer-next"
"C-p" = ":buffer-previous"

[keys.insert]
# Quick escape
j = { k = "normal_mode" }
# Save in insert mode
C-s = ["normal_mode", ":write", "insert_mode"]

[keys.select]
# Indent selection
tab = "indent"
# Outdent selection
S-tab = "unindent"
